/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.diu_practica2;

import java.awt.Color;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Andres
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(210, 251, 247));
        this.setTitle("Money Exchanger");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoRatioExchange = new javax.swing.JLabel();
        valueExchange = new javax.swing.JTextField();
        infoValueExchange = new javax.swing.JLabel();
        valueRatioExchange = new javax.swing.JTextField();
        buttonEuro = new javax.swing.JButton();
        buttonDolar = new javax.swing.JButton();
        resultMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(188, 252, 246));
        setResizable(false);

        infoRatioExchange.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        infoRatioExchange.setText("Introduce exchange ratio Euro (€) to Dolar ($)");

        valueExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueExchangeActionPerformed(evt);
            }
        });

        infoValueExchange.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        infoValueExchange.setText("Introduce quantity to convert");

        valueRatioExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueRatioExchangeActionPerformed(evt);
            }
        });

        buttonEuro.setBackground(new java.awt.Color(153, 153, 153));
        buttonEuro.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        buttonEuro.setText("Convert to Euro");
        buttonEuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonEuro.setBorderPainted(false);
        buttonEuro.setOpaque(true);
        buttonEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEuroActionPerformed(evt);
            }
        });

        buttonDolar.setBackground(new java.awt.Color(153, 153, 153));
        buttonDolar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        buttonDolar.setText("Convert to Dolar");
        buttonDolar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonDolar.setBorderPainted(false);
        buttonDolar.setOpaque(true);
        buttonDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDolarActionPerformed(evt);
            }
        });

        resultMessage.setBackground(new java.awt.Color(255, 255, 153));
        resultMessage.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        resultMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultMessage.setText("Result");
        resultMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        resultMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultMessage.setOpaque(true);
        resultMessage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(resultMessage))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoRatioExchange)
                                    .addComponent(infoValueExchange))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valueRatioExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(buttonEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoRatioExchange)
                    .addComponent(valueExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoValueExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueRatioExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(resultMessage)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueExchangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueExchangeActionPerformed

    private void buttonEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEuroActionPerformed
        double money = 0.0;
        double exchange = 0.0;
        boolean flag = false;
        try {
            money = Double.parseDouble(valueExchange.getText());
            exchange = Double.parseDouble(valueRatioExchange.getText());
            flag = true;
        } catch (NumberFormatException ex) {
             
        JOptionPane.showMessageDialog(null, "You can only introduce digits and the decimal separator \'.\'", "Data Error", 
            JOptionPane.ERROR_MESSAGE);
            resultMessage.setText("Result");
            if(money != 0.0){
                valueRatioExchange.setText("Error");
                valueRatioExchange.setBackground(new Color(254, 53, 53 ) );
            }else{
                valueExchange.setText("Error");
                valueExchange.setBackground(new Color(254, 53, 53 ) );
            }
        }finally{
            DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
            DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();
            symbols.setGroupingSeparator('.');
            formatter.setDecimalFormatSymbols(symbols);
            if(flag){
                resultMessage.setText(formatter.format(exchange/money) + " €");
                valueExchange.setBackground(new Color(255, 255, 255) );
                valueRatioExchange.setBackground(new Color(255, 255, 255) );
            }
        } 
    }//GEN-LAST:event_buttonEuroActionPerformed

    private void valueRatioExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueRatioExchangeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_valueRatioExchangeActionPerformed

    private void buttonDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDolarActionPerformed
        // TODO add your handling code here:
        double money = 0.0;
        double exchange = 0.0;
        boolean flag = false;
        try {
            money = Double.parseDouble(valueExchange.getText());
            exchange = Double.parseDouble(valueRatioExchange.getText());
            flag = true;
        } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "You can only introduce digits and the decimal separator \'.\'", "Data Error", 
            JOptionPane.ERROR_MESSAGE);
            resultMessage.setText("Result");
            if(money != 0.0){
                valueRatioExchange.setText("Error");
                valueRatioExchange.setBackground(new Color(254, 53, 53 ) );
            }else{
                valueExchange.setText("Error");
                valueExchange.setBackground(new Color(254, 53, 53 ) );
            }
        }finally{
            DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
            DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();
            symbols.setGroupingSeparator('.');
            formatter.setDecimalFormatSymbols(symbols);
            if(flag){
                resultMessage.setText(formatter.format(money*exchange) + " $");
                valueExchange.setBackground(new Color(255, 255, 255) );
                valueRatioExchange.setBackground(new Color(255, 255, 255) );
            }
        }
    }//GEN-LAST:event_buttonDolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDolar;
    private javax.swing.JButton buttonEuro;
    private javax.swing.JLabel infoRatioExchange;
    private javax.swing.JLabel infoValueExchange;
    private javax.swing.JLabel resultMessage;
    private javax.swing.JTextField valueExchange;
    private javax.swing.JTextField valueRatioExchange;
    // End of variables declaration//GEN-END:variables
}
